# PREDICT THE SALES FOR A STORE

In [37]:
# import dependencies
import pandas as pd
import numpy as np

In [38]:
data_train = pd.read_csv('train.csv')
data_train

        Store  Dept       Date     Sales IsHoliday
0           1     1   5-Feb-14  24924.50     False
1           1     2   5-Feb-14  50605.27     False
2           1     3   5-Feb-14  13740.12     False
3           1     4   5-Feb-14  39954.04     False
4           1     5   5-Feb-14  32229.38     False
5           1     6   5-Feb-14   5749.03     False
6           1     7   5-Feb-14  21084.08     False
7           1     8   5-Feb-14  40129.01     False
8           1     9   5-Feb-14  16930.99     False
9           1    10   5-Feb-14  30721.50     False
10          1    11   5-Feb-14  24213.18     False
11          1    12   5-Feb-14   8449.54     False
12          1    13   5-Feb-14  41969.29     False
13          1    14   5-Feb-14  19466.91     False
14          1    16   5-Feb-14  10217.55     False
15          1    17   5-Feb-14  13223.76     False
16          1    18   5-Feb-14   4729.50     False
17          1    19   5-Feb-14   1947.05     False
18          1    20   5-Feb-14   5034.10     False
19          1    21   5-Feb-14   8907.63     False
20          1    22   5-Feb-14  13623.98     False
21          1    23   5-Feb-14  24146.49     False
22          1    24   5-Feb-14   8272.90     False
23          1    25   5-Feb-14  11609.50     False
24          1    26   5-Feb-14  11737.12     False
25          1    27   5-Feb-14   2293.00     False
26          1    28   5-Feb-14   1085.29     False
27          1    29   5-Feb-14   7024.95     False
28          1    30   5-Feb-14   5491.00     False
29          1    31   5-Feb-14   3455.92     False
...       ...   ...        ...       ...       ...
344637     45    42  27-Apr-16   5348.03     False
344638     45    44  27-Apr-16   1870.10     False
344639     45    46  27-Apr-16  13424.89     False
344640     45    49  27-Apr-16     20.79     False
344641     45    52  27-Apr-16   1531.23     False
344642     45    54  27-Apr-16     14.88     False
344643     45    55  27-Apr-16   3491.35     False
344644     45    56  27-Apr-16   8074.65     False
344645     45    58  27-Apr-16   1390.00     False
344646     45    59  27-Apr-16    150.41     False
344647     45    60  27-Apr-16     99.00     False
344648     45    67  27-Apr-16   5174.01     False
344649     45    71  27-Apr-16   3437.55     False
344650     45    72  27-Apr-16  30930.48     False
344651     45    74  27-Apr-16   8704.79     False
344652     45    79  27-Apr-16  13491.72     False
344653     45    80  27-Apr-16    844.07     False
344654     45    81  27-Apr-16  14662.04     False
344655     45    82  27-Apr-16  11545.03     False
344656     45    83  27-Apr-16    673.36     False
344657     45    85  27-Apr-16   1395.98     False
344658     45    87  27-Apr-16   4803.12     False
344659     45    90  27-Apr-16  24020.09     False
344660     45    91  27-Apr-16  16203.60     False
344661     45    92  27-Apr-16  46402.05     False
344662     45    93  27-Apr-16   2135.32     False
344663     45    94  27-Apr-16   3109.40     False
344664     45    95  27-Apr-16  50693.76     False
344665     45    97  27-Apr-16   6579.76     False
344666     45    98  27-Apr-16    619.41     False

[344667 rows x 5 columns]

In [39]:
data_features = pd.read_csv('features.csv')
data_features

,Store,Date,Temperature,Fuel_Price,CPI,Unemployment,IsHoliday
0,1,5-Feb-14,5.73,2.572,211.096358,8.106,False
1,2,5-Feb-14,4.55,2.572,210.752605,8.324,False
2,3,5-Feb-14,7.62,2.572,214.424881,7.368,False
3,4,5-Feb-14,6.53,2.598,126.442065,8.623,False
4,5,5-Feb-14,4.28,2.572,211.653972,6.566,False
5,6,5-Feb-14,4.68,2.572,212.622352,7.259,False
6,7,5-Feb-14,-11.93,2.580,189.381697,9.014,False
7,8,5-Feb-14,1.19,2.572,214.471451,6.299,False
8,9,5-Feb-14,3.34,2.572,214.655459,6.415,False
9,10,5-Feb-14,12.41,2.962,126.442065,9.765,False
10,11,5-Feb-14,7.80,2.572,214.424881,7.368,False
11,12,5-Feb-14,9.71,2.962,126.442065,13.975,False
12,13,5-Feb-14,-0.26,2.666,126.442065,8.316,False
13,14,5-Feb-14,-2.61,2.784,181.871190,8.992,False
14,15,5-Feb-14,-6.76,2.954,131.527903,8.350,False
15,16,5-Feb-14,-6.78,2.580,189.381697,7.039,False
16,17,5-Feb-14,-4.94,2.666,126.442065,6.548,False
17,18,5-Feb-14,-5.93,2.788,131.527903,9.202,False
18,19,5-Feb-14,-6.13,2.954,131.527903,8.350,False
19,20,5-Feb-14,-3.38,2.784,204.247194,8.187,False
20,21,5-Feb-14,3.92,2.572,210.752605,8.324,False
21,22,5-Feb-14,-4.24,2.788,135.352461,8.283,False
22,23,5-Feb-14,-9.31,2.788,131.527903,5.892,False
23,24,5-Feb-14,-5.32,2.954,131.527903,8.326,False
24,25,5-Feb-14,-6.06,2.784,204.247194,8.187,False
25,26,5-Feb-14,-12.47,2.788,131.527903,8.488,False
26,27,5-Feb-14,-2.67,2.954,135.352461,8.237,False
27,28,5-Feb-14,9.71,2.962,126.442065,13.975,False
28,29,5-Feb-14,-4.24,2.788,131.527903,10.064,False
29,30,5-Feb-14,3.92,2.572,210.752605,8.324,False
...,...,...,...,...,...,...,...
7575,16,26-Apr-17,1.88,3.568,201.070571,5.324,False
7576,17,26-Apr-17,5.81,3.541,132.716097,5.213,False
7577,18,26-Apr-17,8.88,3.626,139.122613,7.788,False
7578,19,26-Apr-17,8.52,3.806,139.122613,7.806,False
7579,20,26-Apr-17,9.24,3.615,217.742295,7.191,False
7580,21,26-Apr-17,14.81,3.417,224.802531,6.112,False
7581,22,26-Apr-17,9.29,3.626,143.220074,7.176,False
7582,23,26-Apr-17,6.68,3.626,139.122613,3.684,False
7583,24,26-Apr-17,9.17,3.806,139.122613,8.362,False
7584,25,26-Apr-17,7.73,3.615,217.742295,7.191,False
7585,26,26-Apr-17,4.47,3.626,139.122613,6.884,False
7586,27,26-Apr-17,10.49,3.806,143.220074,7.697,False
7587,28,26-Apr-17,21.52,3.889,132.716097,9.874,False
7588,29,26-Apr-17,9.29,3.626,139.122613,8.780,False
7589,30,26-Apr-17,14.81,3.417,224.802531,6.112,False
7590,31,26-Apr-17,14.81,3.417,224.802531,6.112,False
7591,32,26-Apr-17,5.23,3.568,201.070571,6.953,False
7592,33,26-Apr-17,24.75,3.889,132.716097,6.698,False
7593,34,26-Apr-17,14.74,3.397,132.716097,8.796,False
7594,35,26-Apr-17,10.49,3.615,143.220074,8.360,False
7595,36,26-Apr-17,18.00,3.455,223.836362,6.143,False
7596,37,26-Apr-17,18.00,3.417,223.836362,6.143,False
7597,38,26-Apr-17,21.52,3.889,132.716097,9.874,False
7598,39,26-Apr-17,17.75,3.417,223.836362,6.143,False
7599,40,26-Apr-17,6.91,3.626,139.122613,3.684,False
7600,41,26-Apr-17,2.07,3.568,201.070571,5.639,False
7601,42,26-Apr-17,23.67,3.889,132.716097,6.791,False
7602,43,26-Apr-17,19.86,3.417,216.443058,8.796,False
7603,44,26-Apr-17,8.98,3.541,132.716097,4.872,False
7604,45,26-Apr-17,10.36,3.615,193.589304,8.335,False

In [40]:
merged = pd.merge(data_train,data_features,how='inner',on=['Store','Date'])
merged['Week'] = pd.to_datetime(merged['Date']).dt.week
merged

,Store,Dept,Date,Sales,IsHoliday_x,Temperature,Fuel_Price,CPI,Unemployment,IsHoliday_y,Week
0,1,1,5-Feb-14,24924.50,False,5.73,2.572,211.096358,8.106,False,6
1,1,2,5-Feb-14,50605.27,False,5.73,2.572,211.096358,8.106,False,6
2,1,3,5-Feb-14,13740.12,False,5.73,2.572,211.096358,8.106,False,6
3,1,4,5-Feb-14,39954.04,False,5.73,2.572,211.096358,8.106,False,6
4,1,5,5-Feb-14,32229.38,False,5.73,2.572,211.096358,8.106,False,6
5,1,6,5-Feb-14,5749.03,False,5.73,2.572,211.096358,8.106,False,6
6,1,7,5-Feb-14,21084.08,False,5.73,2.572,211.096358,8.106,False,6
7,1,8,5-Feb-14,40129.01,False,5.73,2.572,211.096358,8.106,False,6
8,1,9,5-Feb-14,16930.99,False,5.73,2.572,211.096358,8.106,False,6
9,1,10,5-Feb-14,30721.50,False,5.73,2.572,211.096358,8.106,False,6
10,1,11,5-Feb-14,24213.18,False,5.73,2.572,211.096358,8.106,False,6
11,1,12,5-Feb-14,8449.54,False,5.73,2.572,211.096358,8.106,False,6
12,1,13,5-Feb-14,41969.29,False,5.73,2.572,211.096358,8.106,False,6
13,1,14,5-Feb-14,19466.91,False,5.73,2.572,211.096358,8.106,False,6
14,1,16,5-Feb-14,10217.55,False,5.73,2.572,211.096358,8.106,False,6
15,1,17,5-Feb-14,13223.76,False,5.73,2.572,211.096358,8.106,False,6
16,1,18,5-Feb-14,4729.50,False,5.73,2.572,211.096358,8.106,False,6
17,1,19,5-Feb-14,1947.05,False,5.73,2.572,211.096358,8.106,False,6
18,1,20,5-Feb-14,5034.10,False,5.73,2.572,211.096358,8.106,False,6
19,1,21,5-Feb-14,8907.63,False,5.73,2.572,211.096358,8.106,False,6
20,1,22,5-Feb-14,13623.98,False,5.73,2.572,211.096358,8.106,False,6
21,1,23,5-Feb-14,24146.49,False,5.73,2.572,211.096358,8.106,False,6
22,1,24,5-Feb-14,8272.90,False,5.73,2.572,211.096358,8.106,False,6
23,1,25,5-Feb-14,11609.50,False,5.73,2.572,211.096358,8.106,False,6
24,1,26,5-Feb-14,11737.12,False,5.73,2.572,211.096358,8.106,False,6
25,1,27,5-Feb-14,2293.00,False,5.73,2.572,211.096358,8.106,False,6
26,1,28,5-Feb-14,1085.29,False,5.73,2.572,211.096358,8.106,False,6
27,1,29,5-Feb-14,7024.95,False,5.73,2.572,211.096358,8.106,False,6
28,1,30,5-Feb-14,5491.00,False,5.73,2.572,211.096358,8.106,False,6
29,1,31,5-Feb-14,3455.92,False,5.73,2.572,211.096358,8.106,False,6
...,...,...,...,...,...,...,...,...,...,...,...
344637,45,42,27-Apr-16,5348.03,False,11.78,4.004,190.868006,8.567,False,17
344638,45,44,27-Apr-16,1870.10,False,11.78,4.004,190.868006,8.567,False,17
344639,45,46,27-Apr-16,13424.89,False,11.78,4.004,190.868006,8.567,False,17
344640,45,49,27-Apr-16,20.79,False,11.78,4.004,190.868006,8.567,False,17
344641,45,52,27-Apr-16,1531.23,False,11.78,4.004,190.868006,8.567,False,17
344642,45,54,27-Apr-16,14.88,False,11.78,4.004,190.868006,8.567,False,17
344643,45,55,27-Apr-16,3491.35,False,11.78,4.004,190.868006,8.567,False,17
344644,45,56,27-Apr-16,8074.65,False,11.78,4.004,190.868006,8.567,False,17
344645,45,58,27-Apr-16,1390.00,False,11.78,4.004,190.868006,8.567,False,17
344646,45,59,27-Apr-16,150.41,False,11.78,4.004,190.868006,8.567,False,17
344647,45,60,27-Apr-16,99.00,False,11.78,4.004,190.868006,8.567,False,17
344648,45,67,27-Apr-16,5174.01,False,11.78,4.004,190.868006,8.567,False,17
344649,45,71,27-Apr-16,3437.55,False,11.78,4.004,190.868006,8.567,False,17
344650,45,72,27-Apr-16,30930.48,False,11.78,4.004,190.868006,8.567,False,17
344651,45,74,27-Apr-16,8704.79,False,11.78,4.004,190.868006,8.567,False,17
344652,45,79,27-Apr-16,13491.72,False,11.78,4.004,190.868006,8.567,False,17
344653,45,80,27-Apr-16,844.07,False,11.78,4.004,190.868006,8.567,False,17
344654,45,81,27-Apr-16,14662.04,False,11.78,4.004,190.868006,8.567,False,17
344655,45,82,27-Apr-16,11545.03,False,11.78,4.004,190.868006,8.567,False,17
344656,45,83,27-Apr-16,673.36,False,11.78,4.004,190.868006,8.567,False,17
344657,45,85,27-Apr-16,1395.98,False,11.78,4.004,190.868006,8.567,False,17
344658,45,87,27-Apr-16,4803.12,False,11.78,4.004,190.868006,8.567,False,17
344659,45,90,27-Apr-16,24020.09,False,11.78,4.004,190.868006,8.567,False,17
344660,45,91,27-Apr-16,16203.60,False,11.78,4.004,190.868006,8.567,False,17
344661,45,92,27-Apr-16,46402.05,False,11.78,4.004,190.868006,8.567,False,17
344662,45,93,27-Apr-16,2135.32,False,11.78,4.004,190.868006,8.567,False,17
344663,45,94,27-Apr-16,3109.40,False,11.78,4.004,190.868006,8.567,False,17
344664,45,95,27-Apr-16,50693.76,False,11.78,4.004,190.868006,8.567,False,17
344665,45,97,27-Apr-16,6579.76,False,11.78,4.004,190.868006,8.567,False,17
344666,45,98,27-Apr-16,619.41,False,11.78,4.004,190.868006,8.567,False,17

In [41]:
del merged['Fuel_Price']
del merged['Unemployment']
del merged['Date']
del merged['IsHoliday_x']
merged

        Store  Dept     Sales  Temperature         CPI IsHoliday_y  Week
0           1     1  24924.50         5.73  211.096358       False     6
1           1     2  50605.27         5.73  211.096358       False     6
2           1     3  13740.12         5.73  211.096358       False     6
3           1     4  39954.04         5.73  211.096358       False     6
4           1     5  32229.38         5.73  211.096358       False     6
5           1     6   5749.03         5.73  211.096358       False     6
6           1     7  21084.08         5.73  211.096358       False     6
7           1     8  40129.01         5.73  211.096358       False     6
8           1     9  16930.99         5.73  211.096358       False     6
9           1    10  30721.50         5.73  211.096358       False     6
10          1    11  24213.18         5.73  211.096358       False     6
11          1    12   8449.54         5.73  211.096358       False     6
12          1    13  41969.29         5.73  211.096358       False     6
13          1    14  19466.91         5.73  211.096358       False     6
14          1    16  10217.55         5.73  211.096358       False     6
15          1    17  13223.76         5.73  211.096358       False     6
16          1    18   4729.50         5.73  211.096358       False     6
17          1    19   1947.05         5.73  211.096358       False     6
18          1    20   5034.10         5.73  211.096358       False     6
19          1    21   8907.63         5.73  211.096358       False     6
20          1    22  13623.98         5.73  211.096358       False     6
21          1    23  24146.49         5.73  211.096358       False     6
22          1    24   8272.90         5.73  211.096358       False     6
23          1    25  11609.50         5.73  211.096358       False     6
24          1    26  11737.12         5.73  211.096358       False     6
25          1    27   2293.00         5.73  211.096358       False     6
26          1    28   1085.29         5.73  211.096358       False     6
27          1    29   7024.95         5.73  211.096358       False     6
28          1    30   5491.00         5.73  211.096358       False     6
29          1    31   3455.92         5.73  211.096358       False     6
...       ...   ...       ...          ...         ...         ...   ...
344637     45    42   5348.03        11.78  190.868006       False    17
344638     45    44   1870.10        11.78  190.868006       False    17
344639     45    46  13424.89        11.78  190.868006       False    17
344640     45    49     20.79        11.78  190.868006       False    17
344641     45    52   1531.23        11.78  190.868006       False    17
344642     45    54     14.88        11.78  190.868006       False    17
344643     45    55   3491.35        11.78  190.868006       False    17
344644     45    56   8074.65        11.78  190.868006       False    17
344645     45    58   1390.00        11.78  190.868006       False    17
344646     45    59    150.41        11.78  190.868006       False    17
344647     45    60     99.00        11.78  190.868006       False    17
344648     45    67   5174.01        11.78  190.868006       False    17
344649     45    71   3437.55        11.78  190.868006       False    17
344650     45    72  30930.48        11.78  190.868006       False    17
344651     45    74   8704.79        11.78  190.868006       False    17
344652     45    79  13491.72        11.78  190.868006       False    17
344653     45    80    844.07        11.78  190.868006       False    17
344654     45    81  14662.04        11.78  190.868006       False    17
344655     45    82  11545.03        11.78  190.868006       False    17
344656     45    83    673.36        11.78  190.868006       False    17
344657     45    85   1395.98        11.78  190.868006       False    17
344658     45    87   4803.12        11.78  190.868006       False    17
344659     45    90  24020.09        11.78  190.868006       False    17
344660     45    91  16203.60        11.78  190.868006       False    17
344661     45    92  46402.05        11.78  190.868006       False    17
344662     45    93   2135.32        11.78  190.868006       False    17
344663     45    94   3109.40        11.78  190.868006       False    17
344664     45    95  50693.76        11.78  190.868006       False    17
344665     45    97   6579.76        11.78  190.868006       False    17
344666     45    98    619.41        11.78  190.868006       False    17

[344667 rows x 7 columns]

In [42]:
merged.rename(columns={'IsHoliday_y':'IsHoliday'},inplace=True)
merged

        Store  Dept     Sales  Temperature         CPI IsHoliday  Week
0           1     1  24924.50         5.73  211.096358     False     6
1           1     2  50605.27         5.73  211.096358     False     6
2           1     3  13740.12         5.73  211.096358     False     6
3           1     4  39954.04         5.73  211.096358     False     6
4           1     5  32229.38         5.73  211.096358     False     6
5           1     6   5749.03         5.73  211.096358     False     6
6           1     7  21084.08         5.73  211.096358     False     6
7           1     8  40129.01         5.73  211.096358     False     6
8           1     9  16930.99         5.73  211.096358     False     6
9           1    10  30721.50         5.73  211.096358     False     6
10          1    11  24213.18         5.73  211.096358     False     6
11          1    12   8449.54         5.73  211.096358     False     6
12          1    13  41969.29         5.73  211.096358     False     6
13          1    14  19466.91         5.73  211.096358     False     6
14          1    16  10217.55         5.73  211.096358     False     6
15          1    17  13223.76         5.73  211.096358     False     6
16          1    18   4729.50         5.73  211.096358     False     6
17          1    19   1947.05         5.73  211.096358     False     6
18          1    20   5034.10         5.73  211.096358     False     6
19          1    21   8907.63         5.73  211.096358     False     6
20          1    22  13623.98         5.73  211.096358     False     6
21          1    23  24146.49         5.73  211.096358     False     6
22          1    24   8272.90         5.73  211.096358     False     6
23          1    25  11609.50         5.73  211.096358     False     6
24          1    26  11737.12         5.73  211.096358     False     6
25          1    27   2293.00         5.73  211.096358     False     6
26          1    28   1085.29         5.73  211.096358     False     6
27          1    29   7024.95         5.73  211.096358     False     6
28          1    30   5491.00         5.73  211.096358     False     6
29          1    31   3455.92         5.73  211.096358     False     6
...       ...   ...       ...          ...         ...       ...   ...
344637     45    42   5348.03        11.78  190.868006     False    17
344638     45    44   1870.10        11.78  190.868006     False    17
344639     45    46  13424.89        11.78  190.868006     False    17
344640     45    49     20.79        11.78  190.868006     False    17
344641     45    52   1531.23        11.78  190.868006     False    17
344642     45    54     14.88        11.78  190.868006     False    17
344643     45    55   3491.35        11.78  190.868006     False    17
344644     45    56   8074.65        11.78  190.868006     False    17
344645     45    58   1390.00        11.78  190.868006     False    17
344646     45    59    150.41        11.78  190.868006     False    17
344647     45    60     99.00        11.78  190.868006     False    17
344648     45    67   5174.01        11.78  190.868006     False    17
344649     45    71   3437.55        11.78  190.868006     False    17
344650     45    72  30930.48        11.78  190.868006     False    17
344651     45    74   8704.79        11.78  190.868006     False    17
344652     45    79  13491.72        11.78  190.868006     False    17
344653     45    80    844.07        11.78  190.868006     False    17
344654     45    81  14662.04        11.78  190.868006     False    17
344655     45    82  11545.03        11.78  190.868006     False    17
344656     45    83    673.36        11.78  190.868006     False    17
344657     45    85   1395.98        11.78  190.868006     False    17
344658     45    87   4803.12        11.78  190.868006     False    17
344659     45    90  24020.09        11.78  190.868006     False    17
344660     45    91  16203.60        11.78  190.868006     False    17
344661     45    92  46402.05        11.78  190.868006     False    17
344662     45    93   2135.32        11.78  190.868006     False    17
344663     45    94   3109.40        11.78  190.868006     False    17
344664     45    95  50693.76        11.78  190.868006     False    17
344665     45    97   6579.76        11.78  190.868006     False    17
344666     45    98    619.41        11.78  190.868006     False    17

[344667 rows x 7 columns]

In [43]:
merged.IsHoliday = merged.IsHoliday.astype(np.int32)
merged

        Store  Dept     Sales  Temperature         CPI  IsHoliday  Week
0           1     1  24924.50         5.73  211.096358          0     6
1           1     2  50605.27         5.73  211.096358          0     6
2           1     3  13740.12         5.73  211.096358          0     6
3           1     4  39954.04         5.73  211.096358          0     6
4           1     5  32229.38         5.73  211.096358          0     6
5           1     6   5749.03         5.73  211.096358          0     6
6           1     7  21084.08         5.73  211.096358          0     6
7           1     8  40129.01         5.73  211.096358          0     6
8           1     9  16930.99         5.73  211.096358          0     6
9           1    10  30721.50         5.73  211.096358          0     6
10          1    11  24213.18         5.73  211.096358          0     6
11          1    12   8449.54         5.73  211.096358          0     6
12          1    13  41969.29         5.73  211.096358          0     6
13          1    14  19466.91         5.73  211.096358          0     6
14          1    16  10217.55         5.73  211.096358          0     6
15          1    17  13223.76         5.73  211.096358          0     6
16          1    18   4729.50         5.73  211.096358          0     6
17          1    19   1947.05         5.73  211.096358          0     6
18          1    20   5034.10         5.73  211.096358          0     6
19          1    21   8907.63         5.73  211.096358          0     6
20          1    22  13623.98         5.73  211.096358          0     6
21          1    23  24146.49         5.73  211.096358          0     6
22          1    24   8272.90         5.73  211.096358          0     6
23          1    25  11609.50         5.73  211.096358          0     6
24          1    26  11737.12         5.73  211.096358          0     6
25          1    27   2293.00         5.73  211.096358          0     6
26          1    28   1085.29         5.73  211.096358          0     6
27          1    29   7024.95         5.73  211.096358          0     6
28          1    30   5491.00         5.73  211.096358          0     6
29          1    31   3455.92         5.73  211.096358          0     6
...       ...   ...       ...          ...         ...        ...   ...
344637     45    42   5348.03        11.78  190.868006          0    17
344638     45    44   1870.10        11.78  190.868006          0    17
344639     45    46  13424.89        11.78  190.868006          0    17
344640     45    49     20.79        11.78  190.868006          0    17
344641     45    52   1531.23        11.78  190.868006          0    17
344642     45    54     14.88        11.78  190.868006          0    17
344643     45    55   3491.35        11.78  190.868006          0    17
344644     45    56   8074.65        11.78  190.868006          0    17
344645     45    58   1390.00        11.78  190.868006          0    17
344646     45    59    150.41        11.78  190.868006          0    17
344647     45    60     99.00        11.78  190.868006          0    17
344648     45    67   5174.01        11.78  190.868006          0    17
344649     45    71   3437.55        11.78  190.868006          0    17
344650     45    72  30930.48        11.78  190.868006          0    17
344651     45    74   8704.79        11.78  190.868006          0    17
344652     45    79  13491.72        11.78  190.868006          0    17
344653     45    80    844.07        11.78  190.868006          0    17
344654     45    81  14662.04        11.78  190.868006          0    17
344655     45    82  11545.03        11.78  190.868006          0    17
344656     45    83    673.36        11.78  190.868006          0    17
344657     45    85   1395.98        11.78  190.868006          0    17
344658     45    87   4803.12        11.78  190.868006          0    17
344659     45    90  24020.09        11.78  190.868006          0    17
344660     45    91  16203.60        11.78  190.868006          0    17
344661     45    92  46402.05        11.78  190.868006          0    17
344662     45    93   2135.32        11.78  190.868006          0    17
344663     45    94   3109.40        11.78  190.868006          0    17
344664     45    95  50693.76        11.78  190.868006          0    17
344665     45    97   6579.76        11.78  190.868006          0    17
344666     45    98    619.41        11.78  190.868006          0    17

[344667 rows x 7 columns]

In [44]:
sales = merged['Sales']
del merged['Sales']
sales = sales.as_matrix()
sales

array([ 24924.5 ,  50605.27,  13740.12, ...,  50693.76,   6579.76,
          619.41])

In [45]:
train_data = merged.as_matrix()
train_data

array([[   1.       ,    1.       ,    5.73     ,  211.0963582,
           0.       ,    6.       ],
       [   1.       ,    2.       ,    5.73     ,  211.0963582,
           0.       ,    6.       ],
       [   1.       ,    3.       ,    5.73     ,  211.0963582,
           0.       ,    6.       ],
       ...,
       [  45.       ,   95.       ,   11.78     ,  190.8680064,
           0.       ,   17.       ],
       [  45.       ,   97.       ,   11.78     ,  190.8680064,
           0.       ,   17.       ],
       [  45.       ,   98.       ,   11.78     ,  190.8680064,
           0.       ,   17.       ]])

In [46]:
from sklearn.model_selection import TimeSeriesSplit,train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestRegressor as rfr

In [47]:
X_train,X_test,y_train,y_test = train_test_split(train_data,sales,test_size=0.2,random_state=42)
model = rfr(verbose=1)
model.fit(X_train,y_train)
score1 = model.score(X_test,y_test)
score2 = model.score(X_train,y_train)

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   12.2s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    1.5s finished

In [48]:
score1
score2
print("Testing Score : %0.2f \n Training Score : %0.2f" %(score1,score2))

Testing Score : 0.96
 Training Score : 0.99

# PREDICTION

In [13]:
data_test = pd.read_csv('test.csv')
data_test

        Store  Dept       Date IsHoliday  SalesForecast
0           1     1   4-May-16     False            NaN
1           1     2   4-May-16     False            NaN
2           1     3   4-May-16     False            NaN
3           1     4   4-May-16     False            NaN
4           1     5   4-May-16     False            NaN
5           1     6   4-May-16     False            NaN
6           1     7   4-May-16     False            NaN
7           1     8   4-May-16     False            NaN
8           1     9   4-May-16     False            NaN
9           1    10   4-May-16     False            NaN
10          1    11   4-May-16     False            NaN
11          1    12   4-May-16     False            NaN
12          1    13   4-May-16     False            NaN
13          1    14   4-May-16     False            NaN
14          1    16   4-May-16     False            NaN
15          1    17   4-May-16     False            NaN
16          1    18   4-May-16     False            NaN
17          1    19   4-May-16     False            NaN
18          1    20   4-May-16     False            NaN
19          1    21   4-May-16     False            NaN
20          1    22   4-May-16     False            NaN
21          1    23   4-May-16     False            NaN
22          1    24   4-May-16     False            NaN
23          1    25   4-May-16     False            NaN
24          1    26   4-May-16     False            NaN
25          1    27   4-May-16     False            NaN
26          1    28   4-May-16     False            NaN
27          1    29   4-May-16     False            NaN
28          1    30   4-May-16     False            NaN
29          1    31   4-May-16     False            NaN
...       ...   ...        ...       ...            ...
153775     45    42  26-Apr-17     False            NaN
153776     45    44  26-Apr-17     False            NaN
153777     45    45  26-Apr-17     False            NaN
153778     45    46  26-Apr-17     False            NaN
153779     45    49  26-Apr-17     False            NaN
153780     45    52  26-Apr-17     False            NaN
153781     45    55  26-Apr-17     False            NaN
153782     45    56  26-Apr-17     False            NaN
153783     45    58  26-Apr-17     False            NaN
153784     45    59  26-Apr-17     False            NaN
153785     45    60  26-Apr-17     False            NaN
153786     45    67  26-Apr-17     False            NaN
153787     45    71  26-Apr-17     False            NaN
153788     45    72  26-Apr-17     False            NaN
153789     45    74  26-Apr-17     False            NaN
153790     45    79  26-Apr-17     False            NaN
153791     45    80  26-Apr-17     False            NaN
153792     45    81  26-Apr-17     False            NaN
153793     45    82  26-Apr-17     False            NaN
153794     45    83  26-Apr-17     False            NaN
153795     45    85  26-Apr-17     False            NaN
153796     45    87  26-Apr-17     False            NaN
153797     45    90  26-Apr-17     False            NaN
153798     45    91  26-Apr-17     False            NaN
153799     45    92  26-Apr-17     False            NaN
153800     45    93  26-Apr-17     False            NaN
153801     45    94  26-Apr-17     False            NaN
153802     45    95  26-Apr-17     False            NaN
153803     45    97  26-Apr-17     False            NaN
153804     45    98  26-Apr-17     False            NaN

[153805 rows x 5 columns]

In [14]:
test_merged = pd.merge(data_test,data_features,how='inner',on=['Store','Date'])
test_merged['Week'] = pd.to_datetime(test_merged['Date']).dt.week
test_merged

,Store,Dept,Date,IsHoliday_x,SalesForecast,Temperature,Fuel_Price,CPI,Unemployment,IsHoliday_y,Week
0,1,1,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
1,1,2,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
2,1,3,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
3,1,4,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
4,1,5,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
5,1,6,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
6,1,7,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
7,1,8,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
8,1,9,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
9,1,10,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
10,1,11,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
11,1,12,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
12,1,13,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
13,1,14,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
14,1,16,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
15,1,17,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
16,1,18,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
17,1,19,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
18,1,20,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
19,1,21,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
20,1,22,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
21,1,23,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
22,1,24,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
23,1,25,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
24,1,26,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
25,1,27,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
26,1,28,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
27,1,29,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
28,1,30,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
29,1,31,4-May-16,False,NaN,24.19,3.749,221.671800,7.143,False,18
...,...,...,...,...,...,...,...,...,...,...,...
153775,45,42,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153776,45,44,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153777,45,45,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153778,45,46,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153779,45,49,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153780,45,52,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153781,45,55,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153782,45,56,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153783,45,58,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153784,45,59,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153785,45,60,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153786,45,67,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153787,45,71,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153788,45,72,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153789,45,74,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153790,45,79,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153791,45,80,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153792,45,81,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153793,45,82,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153794,45,83,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153795,45,85,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153796,45,87,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153797,45,90,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153798,45,91,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153799,45,92,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153800,45,93,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153801,45,94,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153802,45,95,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153803,45,97,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17
153804,45,98,26-Apr-17,False,NaN,10.36,3.615,193.589304,8.335,False,17

In [15]:
del test_merged['Fuel_Price']
del test_merged['Unemployment']
del test_merged['Date']
del test_merged['IsHoliday_x']
test_merged

        Store  Dept  SalesForecast  Temperature         CPI IsHoliday_y  Week
0           1     1            NaN        24.19  221.671800       False    18
1           1     2            NaN        24.19  221.671800       False    18
2           1     3            NaN        24.19  221.671800       False    18
3           1     4            NaN        24.19  221.671800       False    18
4           1     5            NaN        24.19  221.671800       False    18
5           1     6            NaN        24.19  221.671800       False    18
6           1     7            NaN        24.19  221.671800       False    18
7           1     8            NaN        24.19  221.671800       False    18
8           1     9            NaN        24.19  221.671800       False    18
9           1    10            NaN        24.19  221.671800       False    18
10          1    11            NaN        24.19  221.671800       False    18
11          1    12            NaN        24.19  221.671800       False    18
12          1    13            NaN        24.19  221.671800       False    18
13          1    14            NaN        24.19  221.671800       False    18
14          1    16            NaN        24.19  221.671800       False    18
15          1    17            NaN        24.19  221.671800       False    18
16          1    18            NaN        24.19  221.671800       False    18
17          1    19            NaN        24.19  221.671800       False    18
18          1    20            NaN        24.19  221.671800       False    18
19          1    21            NaN        24.19  221.671800       False    18
20          1    22            NaN        24.19  221.671800       False    18
21          1    23            NaN        24.19  221.671800       False    18
22          1    24            NaN        24.19  221.671800       False    18
23          1    25            NaN        24.19  221.671800       False    18
24          1    26            NaN        24.19  221.671800       False    18
25          1    27            NaN        24.19  221.671800       False    18
26          1    28            NaN        24.19  221.671800       False    18
27          1    29            NaN        24.19  221.671800       False    18
28          1    30            NaN        24.19  221.671800       False    18
29          1    31            NaN        24.19  221.671800       False    18
...       ...   ...            ...          ...         ...         ...   ...
153775     45    42            NaN        10.36  193.589304       False    17
153776     45    44            NaN        10.36  193.589304       False    17
153777     45    45            NaN        10.36  193.589304       False    17
153778     45    46            NaN        10.36  193.589304       False    17
153779     45    49            NaN        10.36  193.589304       False    17
153780     45    52            NaN        10.36  193.589304       False    17
153781     45    55            NaN        10.36  193.589304       False    17
153782     45    56            NaN        10.36  193.589304       False    17
153783     45    58            NaN        10.36  193.589304       False    17
153784     45    59            NaN        10.36  193.589304       False    17
153785     45    60            NaN        10.36  193.589304       False    17
153786     45    67            NaN        10.36  193.589304       False    17
153787     45    71            NaN        10.36  193.589304       False    17
153788     45    72            NaN        10.36  193.589304       False    17
153789     45    74            NaN        10.36  193.589304       False    17
153790     45    79            NaN        10.36  193.589304       False    17
153791     45    80            NaN        10.36  193.589304       False    17
153792     45    81            NaN        10.36  193.589304       False    17
153793     45    82            NaN        10.36  193.589304       False    17
153794     45    83            NaN        10.36  193.589304       False    17
153795     45    85            NaN        10.36  193.589304       False    17
153796     45    87            NaN        10.36  193.589304       False    17
153797     45    90            NaN        10.36  193.589304       False    17
153798     45    91            NaN        10.36  193.589304       False    17
153799     45    92            NaN        10.36  193.589304       False    17
153800     45    93            NaN        10.36  193.589304       False    17
153801     45    94            NaN        10.36  193.589304       False    17
153802     45    95            NaN        10.36  193.589304       False    17
153803     45    97            NaN        10.36  193.589304       False    17
153804     45    98            NaN        10.36  193.589304       False    17

[153805 rows x 7 columns]

In [16]:
test_merged.rename(columns={'IsHoliday_y':'IsHoliday'},inplace=True)
test_merged

        Store  Dept  SalesForecast  Temperature         CPI IsHoliday  Week
0           1     1            NaN        24.19  221.671800     False    18
1           1     2            NaN        24.19  221.671800     False    18
2           1     3            NaN        24.19  221.671800     False    18
3           1     4            NaN        24.19  221.671800     False    18
4           1     5            NaN        24.19  221.671800     False    18
5           1     6            NaN        24.19  221.671800     False    18
6           1     7            NaN        24.19  221.671800     False    18
7           1     8            NaN        24.19  221.671800     False    18
8           1     9            NaN        24.19  221.671800     False    18
9           1    10            NaN        24.19  221.671800     False    18
10          1    11            NaN        24.19  221.671800     False    18
11          1    12            NaN        24.19  221.671800     False    18
12          1    13            NaN        24.19  221.671800     False    18
13          1    14            NaN        24.19  221.671800     False    18
14          1    16            NaN        24.19  221.671800     False    18
15          1    17            NaN        24.19  221.671800     False    18
16          1    18            NaN        24.19  221.671800     False    18
17          1    19            NaN        24.19  221.671800     False    18
18          1    20            NaN        24.19  221.671800     False    18
19          1    21            NaN        24.19  221.671800     False    18
20          1    22            NaN        24.19  221.671800     False    18
21          1    23            NaN        24.19  221.671800     False    18
22          1    24            NaN        24.19  221.671800     False    18
23          1    25            NaN        24.19  221.671800     False    18
24          1    26            NaN        24.19  221.671800     False    18
25          1    27            NaN        24.19  221.671800     False    18
26          1    28            NaN        24.19  221.671800     False    18
27          1    29            NaN        24.19  221.671800     False    18
28          1    30            NaN        24.19  221.671800     False    18
29          1    31            NaN        24.19  221.671800     False    18
...       ...   ...            ...          ...         ...       ...   ...
153775     45    42            NaN        10.36  193.589304     False    17
153776     45    44            NaN        10.36  193.589304     False    17
153777     45    45            NaN        10.36  193.589304     False    17
153778     45    46            NaN        10.36  193.589304     False    17
153779     45    49            NaN        10.36  193.589304     False    17
153780     45    52            NaN        10.36  193.589304     False    17
153781     45    55            NaN        10.36  193.589304     False    17
153782     45    56            NaN        10.36  193.589304     False    17
153783     45    58            NaN        10.36  193.589304     False    17
153784     45    59            NaN        10.36  193.589304     False    17
153785     45    60            NaN        10.36  193.589304     False    17
153786     45    67            NaN        10.36  193.589304     False    17
153787     45    71            NaN        10.36  193.589304     False    17
153788     45    72            NaN        10.36  193.589304     False    17
153789     45    74            NaN        10.36  193.589304     False    17
153790     45    79            NaN        10.36  193.589304     False    17
153791     45    80            NaN        10.36  193.589304     False    17
153792     45    81            NaN        10.36  193.589304     False    17
153793     45    82            NaN        10.36  193.589304     False    17
153794     45    83            NaN        10.36  193.589304     False    17
153795     45    85            NaN        10.36  193.589304     False    17
153796     45    87            NaN        10.36  193.589304     False    17
153797     45    90            NaN        10.36  193.589304     False    17
153798     45    91            NaN        10.36  193.589304     False    17
153799     45    92            NaN        10.36  193.589304     False    17
153800     45    93            NaN        10.36  193.589304     False    17
153801     45    94            NaN        10.36  193.589304     False    17
153802     45    95            NaN        10.36  193.589304     False    17
153803     45    97            NaN        10.36  193.589304     False    17
153804     45    98            NaN        10.36  193.589304     False    17

[153805 rows x 7 columns]

In [17]:
test_merged.IsHoliday = test_merged.IsHoliday.astype(np.int32)
test_merged

        Store  Dept  SalesForecast  Temperature         CPI  IsHoliday  Week
0           1     1            NaN        24.19  221.671800          0    18
1           1     2            NaN        24.19  221.671800          0    18
2           1     3            NaN        24.19  221.671800          0    18
3           1     4            NaN        24.19  221.671800          0    18
4           1     5            NaN        24.19  221.671800          0    18
5           1     6            NaN        24.19  221.671800          0    18
6           1     7            NaN        24.19  221.671800          0    18
7           1     8            NaN        24.19  221.671800          0    18
8           1     9            NaN        24.19  221.671800          0    18
9           1    10            NaN        24.19  221.671800          0    18
10          1    11            NaN        24.19  221.671800          0    18
11          1    12            NaN        24.19  221.671800          0    18
12          1    13            NaN        24.19  221.671800          0    18
13          1    14            NaN        24.19  221.671800          0    18
14          1    16            NaN        24.19  221.671800          0    18
15          1    17            NaN        24.19  221.671800          0    18
16          1    18            NaN        24.19  221.671800          0    18
17          1    19            NaN        24.19  221.671800          0    18
18          1    20            NaN        24.19  221.671800          0    18
19          1    21            NaN        24.19  221.671800          0    18
20          1    22            NaN        24.19  221.671800          0    18
21          1    23            NaN        24.19  221.671800          0    18
22          1    24            NaN        24.19  221.671800          0    18
23          1    25            NaN        24.19  221.671800          0    18
24          1    26            NaN        24.19  221.671800          0    18
25          1    27            NaN        24.19  221.671800          0    18
26          1    28            NaN        24.19  221.671800          0    18
27          1    29            NaN        24.19  221.671800          0    18
28          1    30            NaN        24.19  221.671800          0    18
29          1    31            NaN        24.19  221.671800          0    18
...       ...   ...            ...          ...         ...        ...   ...
153775     45    42            NaN        10.36  193.589304          0    17
153776     45    44            NaN        10.36  193.589304          0    17
153777     45    45            NaN        10.36  193.589304          0    17
153778     45    46            NaN        10.36  193.589304          0    17
153779     45    49            NaN        10.36  193.589304          0    17
153780     45    52            NaN        10.36  193.589304          0    17
153781     45    55            NaN        10.36  193.589304          0    17
153782     45    56            NaN        10.36  193.589304          0    17
153783     45    58            NaN        10.36  193.589304          0    17
153784     45    59            NaN        10.36  193.589304          0    17
153785     45    60            NaN        10.36  193.589304          0    17
153786     45    67            NaN        10.36  193.589304          0    17
153787     45    71            NaN        10.36  193.589304          0    17
153788     45    72            NaN        10.36  193.589304          0    17
153789     45    74            NaN        10.36  193.589304          0    17
153790     45    79            NaN        10.36  193.589304          0    17
153791     45    80            NaN        10.36  193.589304          0    17
153792     45    81            NaN        10.36  193.589304          0    17
153793     45    82            NaN        10.36  193.589304          0    17
153794     45    83            NaN        10.36  193.589304          0    17
153795     45    85            NaN        10.36  193.589304          0    17
153796     45    87            NaN        10.36  193.589304          0    17
153797     45    90            NaN        10.36  193.589304          0    17
153798     45    91            NaN        10.36  193.589304          0    17
153799     45    92            NaN        10.36  193.589304          0    17
153800     45    93            NaN        10.36  193.589304          0    17
153801     45    94            NaN        10.36  193.589304          0    17
153802     45    95            NaN        10.36  193.589304          0    17
153803     45    97            NaN        10.36  193.589304          0    17
153804     45    98            NaN        10.36  193.589304          0    17

[153805 rows x 7 columns]

In [18]:
sales = test_merged['SalesForecast']
del test_merged['SalesForecast']
merged

        Store  Dept  Temperature         CPI  IsHoliday  Week
0           1     1         5.73  211.096358          0     6
1           1     2         5.73  211.096358          0     6
2           1     3         5.73  211.096358          0     6
3           1     4         5.73  211.096358          0     6
4           1     5         5.73  211.096358          0     6
5           1     6         5.73  211.096358          0     6
6           1     7         5.73  211.096358          0     6
7           1     8         5.73  211.096358          0     6
8           1     9         5.73  211.096358          0     6
9           1    10         5.73  211.096358          0     6
10          1    11         5.73  211.096358          0     6
11          1    12         5.73  211.096358          0     6
12          1    13         5.73  211.096358          0     6
13          1    14         5.73  211.096358          0     6
14          1    16         5.73  211.096358          0     6
15          1    17         5.73  211.096358          0     6
16          1    18         5.73  211.096358          0     6
17          1    19         5.73  211.096358          0     6
18          1    20         5.73  211.096358          0     6
19          1    21         5.73  211.096358          0     6
20          1    22         5.73  211.096358          0     6
21          1    23         5.73  211.096358          0     6
22          1    24         5.73  211.096358          0     6
23          1    25         5.73  211.096358          0     6
24          1    26         5.73  211.096358          0     6
25          1    27         5.73  211.096358          0     6
26          1    28         5.73  211.096358          0     6
27          1    29         5.73  211.096358          0     6
28          1    30         5.73  211.096358          0     6
29          1    31         5.73  211.096358          0     6
...       ...   ...          ...         ...        ...   ...
344637     45    42        11.78  190.868006          0    17
344638     45    44        11.78  190.868006          0    17
344639     45    46        11.78  190.868006          0    17
344640     45    49        11.78  190.868006          0    17
344641     45    52        11.78  190.868006          0    17
344642     45    54        11.78  190.868006          0    17
344643     45    55        11.78  190.868006          0    17
344644     45    56        11.78  190.868006          0    17
344645     45    58        11.78  190.868006          0    17
344646     45    59        11.78  190.868006          0    17
344647     45    60        11.78  190.868006          0    17
344648     45    67        11.78  190.868006          0    17
344649     45    71        11.78  190.868006          0    17
344650     45    72        11.78  190.868006          0    17
344651     45    74        11.78  190.868006          0    17
344652     45    79        11.78  190.868006          0    17
344653     45    80        11.78  190.868006          0    17
344654     45    81        11.78  190.868006          0    17
344655     45    82        11.78  190.868006          0    17
344656     45    83        11.78  190.868006          0    17
344657     45    85        11.78  190.868006          0    17
344658     45    87        11.78  190.868006          0    17
344659     45    90        11.78  190.868006          0    17
344660     45    91        11.78  190.868006          0    17
344661     45    92        11.78  190.868006          0    17
344662     45    93        11.78  190.868006          0    17
344663     45    94        11.78  190.868006          0    17
344664     45    95        11.78  190.868006          0    17
344665     45    97        11.78  190.868006          0    17
344666     45    98        11.78  190.868006          0    17

[344667 rows x 6 columns]

In [19]:
predict_data = test_merged.as_matrix()
predict_data

array([[   1.      ,    1.      ,   24.19    ,  221.6718  ,    0.      ,
          18.      ],
       [   1.      ,    2.      ,   24.19    ,  221.6718  ,    0.      ,
          18.      ],
       [   1.      ,    3.      ,   24.19    ,  221.6718  ,    0.      ,
          18.      ],
       ...,
       [  45.      ,   95.      ,   10.36    ,  193.589304,    0.      ,
          17.      ],
       [  45.      ,   97.      ,   10.36    ,  193.589304,    0.      ,
          17.      ],
       [  45.      ,   98.      ,   10.36    ,  193.589304,    0.      ,
          17.      ]])

In [20]:
predictions = model.predict(predict_data)
predictions

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.6s finished

array([ 17295.681,  45474.298,   8373.821, ...,  48711.264,   6200.693,
          696.224])

In [22]:
final_df = pd.read_csv('test.csv')
final_df['SalesForecast'] = predictions
final_df.to_csv('predictions.csv')
final_df

        Store  Dept       Date IsHoliday  SalesForecast
0           1     1   4-May-16     False      17295.681
1           1     2   4-May-16     False      45474.298
2           1     3   4-May-16     False       8373.821
3           1     4   4-May-16     False      40049.834
4           1     5   4-May-16     False      16848.971
5           1     6   4-May-16     False       3781.457
6           1     7   4-May-16     False      23956.576
7           1     8   4-May-16     False      41008.546
8           1     9   4-May-16     False      35318.393
9           1    10   4-May-16     False      33084.713
10          1    11   4-May-16     False      27501.302
11          1    12   4-May-16     False      10858.959
12          1    13   4-May-16     False      40870.778
13          1    14   4-May-16     False      14581.040
14          1    16   4-May-16     False      52505.231
15          1    17   4-May-16     False       7843.130
16          1    18   4-May-16     False       4373.264
17          1    19   4-May-16     False        822.894
18          1    20   4-May-16     False       3896.064
19          1    21   4-May-16     False       8458.163
20          1    22   4-May-16     False       6321.302
21          1    23   4-May-16     False      20816.107
22          1    24   4-May-16     False       3999.396
23          1    25   4-May-16     False      11358.234
24          1    26   4-May-16     False       6060.496
25          1    27   4-May-16     False        966.427
26          1    28   4-May-16     False        509.681
27          1    29   4-May-16     False       4400.397
28          1    30   4-May-16     False       3079.320
29          1    31   4-May-16     False       1328.620
...       ...   ...        ...       ...            ...
153775     45    42  26-Apr-17     False       5166.811
153776     45    44  26-Apr-17     False       2032.515
153777     45    45  26-Apr-17     False         29.315
153778     45    46  26-Apr-17     False      13524.828
153779     45    49  26-Apr-17     False         24.549
153780     45    52  26-Apr-17     False       1560.802
153781     45    55  26-Apr-17     False       4504.298
153782     45    56  26-Apr-17     False      11315.824
153783     45    58  26-Apr-17     False       1956.500
153784     45    59  26-Apr-17     False        187.551
153785     45    60  26-Apr-17     False        154.800
153786     45    67  26-Apr-17     False       7575.598
153787     45    71  26-Apr-17     False       4797.749
153788     45    72  26-Apr-17     False      30699.819
153789     45    74  26-Apr-17     False       9069.965
153790     45    79  26-Apr-17     False      15149.236
153791     45    80  26-Apr-17     False       6231.741
153792     45    81  26-Apr-17     False      14541.537
153793     45    82  26-Apr-17     False      14143.203
153794     45    83  26-Apr-17     False       1521.170
153795     45    85  26-Apr-17     False       1965.315
153796     45    87  26-Apr-17     False       9781.506
153797     45    90  26-Apr-17     False      26104.619
153798     45    91  26-Apr-17     False      15948.250
153799     45    92  26-Apr-17     False      48774.708
153800     45    93  26-Apr-17     False       2233.080
153801     45    94  26-Apr-17     False       2967.475
153802     45    95  26-Apr-17     False      48711.264
153803     45    97  26-Apr-17     False       6200.693
153804     45    98  26-Apr-17     False        696.224

[153805 rows x 5 columns]